version: '3.1'

services:

  db:
    image: postgres
    container_name: test_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:${POSTGRES_PORT}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"