//! Module contains everything needed to handle JWT tokens generated by the frontend.
//! Encoding functions are included, but for testing purposes only, hence their 'private' status.

use dotenvy::dotenv;
use jsonwebtoken::{decode, Algorithm, DecodingKey, TokenData, Validation};
use serde::{Deserialize, Serialize};
use std::env;
use std::fs;
use uuid::Uuid;

#[cfg(test)]
use {
    jsonwebtoken::{encode, EncodingKey, Header},
    std::time::{SystemTime, UNIX_EPOCH},
};
use crate::router::AppState;
use crate::core::error::ApiError;


/// Struct representing the data we expect in the JWT TokenData as claims.
pub struct PublicClaimData {
    /// Unique user id.
    pub uuid: Uuid,
    /// User's full name.
    pub name: String,
    /// User's email address.
    pub email: String,
}

/// Expected JWT TokenData claims from the frontend.
#[derive(Deserialize, Serialize, Debug, Clone, PartialEq, Eq)]
pub struct Claims {
    /// Authenticated user's UUID (unique user ID, not just a sequential number).
    uuid: Uuid,
    /// Authenticated user's name.
    name: String,
    /// Authenticated user's email.
    email: String,
    /// Token expiration time in seconds from EPOCH.
    exp: usize,
}
impl Claims {
    /// Create a new Claims. Expiration should be in seconds from the claim creation on.
    /// Recommended exp: 5 to 15 minutes for API requests.
    ///
    /// The UUID is generated in-situ when not specified.
    ///
    /// This function is sealed behind `#[cfg(test)]` as it's not intended to generate claims and tokens
    /// from the API side.
    ///
    /// ## Example
    /// ```
    /// let claims = Claims::new(
    ///     String::from("John Doe"),
    ///     String::from("john.doe@gmail.com"),
    ///     5 * 60 // 5 minutes from token creation on.
    /// )
    /// ```
    #[cfg(test)]
    pub fn new(uuid: Option<Uuid>, name: String, email: String, exp: usize) -> Self {
        let now = SystemTime::now();
        let exp = now.duration_since(UNIX_EPOCH).unwrap().as_secs() as usize + exp;
        let uuid = uuid.unwrap_or_else(Uuid::new_v4);

        Claims {
            uuid,
            name,
            email,
            exp,
        }
    }

    /// Get all user details from the claim.
    pub fn get_user_details(&self) -> PublicClaimData {
        PublicClaimData {
            uuid: self.uuid.clone(),
            name: self.name.clone(),
            email: self.email.clone(),
        }
    }

    /// Get the uuid from the claim
    pub fn uuid(&self) -> Uuid {
        self.uuid
    }

    /// Get the name of the user from the claim.
    pub fn name(&self) -> String {
        self.name.clone()
    }

    /// Get the email address from the claim.
    pub fn email(&self) -> String {
        self.email.clone()
    }
}

/// Jsonwebtoken struct. Contains an initialized encoder and decoder. Relies on `.env` to have
/// an auth secret to be set in variable `JWT_SECRET`.
///
/// ## Testing
///
/// `encoding_key` is only generated in test mode under `#[cfg(test)]` since we don't wan to generate tokens in the backend.
#[derive(Clone)]
pub struct JWT {
    algorithm: Algorithm,
    decoding_key: DecodingKey,
    #[cfg(test)]
    encoding_key: EncodingKey,
}
impl Default for JWT {
    fn default() -> Self {
        JWT::new()
    }
}
impl JWT {
    /// Generate a new instance of JWT. Contains a re-usable [EncodingKey].
    ///
    /// ## Testing
    ///
    /// For testing cases, field `encoding_key` is generated under `#[cfg(test)]`
    fn new() -> Self {
        dotenv().ok();
        let secret = env::var("JWT_SECRET").expect("JWT_SECRET must be set in .env file");
        let decoding_key = DecodingKey::from_secret(secret.as_bytes());

        #[cfg(test)]
        let encoding_key = EncodingKey::from_secret(secret.as_bytes());

        JWT {
            // For Secret based signing, we use ES256.
            algorithm: Algorithm::ES256,
            decoding_key,
            #[cfg(test)]
            encoding_key,
        }
    }

    fn new_from_pem(f: String) -> Self {
        let public_key = std::fs::read_to_string(f.clone() + ".pub").expect(&format!("Unable to read public key {}", f.clone() + ".pub"));
        #[cfg(test)]
        let private_key = std::fs::read_to_string(&f).expect(&format!("Unable to read public key {}", f.clone()));
        #[cfg(test)]
        dbg!(&private_key);

        let decoding_key = DecodingKey::from_rsa_pem(public_key.as_bytes()).unwrap();
        #[cfg(test)]
        let encoding_key = EncodingKey::from_rsa_pem(private_key.as_bytes()).unwrap();

        JWT {
            algorithm: Algorithm::RS256,
            decoding_key,
            #[cfg(test)]
            encoding_key,
        }
    }

    /// Decode an incoming token using JWT. The token issues should be using the same jwt secret as
    /// this backend.
    ///
    /// Only valid for `HS256` secrets/encoded data.
    ///
    /// ## Future
    ///
    /// Once more reliable, a public and private key system should be set up? Unsure if this is
    /// beneficial if the frontend uses AuthJS.
    pub fn decode(&self, token: String) -> Result<TokenData<Claims>, jsonwebtoken::errors::Error> {
        decode(&token, &self.decoding_key, &Validation::new(self.algorithm))
    }

    /// Encoding a claim into a json web token. For testing purposes.
    #[cfg(test)]
    pub fn encode(&self, claims: Claims) -> Result<String, jsonwebtoken::errors::Error> {
        encode(&Header::new(self.algorithm), &claims, &self.encoding_key)
    }
}

/// Extracts the user's Uuid from the request's authorization header.
pub fn extract_headers_uuid(headers: axum::http::HeaderMap, state: &AppState) -> Result<uuid::Uuid, ApiError> {
    let token = headers.get(axum::http::header::AUTHORIZATION)
        .and_then(|header| header.to_str().ok())
        .ok_or_else(|| ApiError::AuthorizationHeader {
            expected: String::from("token"),
            found: String::from("None")
        })?
        .strip_prefix("Bearer ").unwrap();

    let token_data = state.jwt.decode(token.to_string()).map_err(|err| ApiError::JWTDecode(err.to_string()))?;

    Ok(token_data.claims.uuid())
}

#[cfg(test)]
mod tests {
    use super::*;

    mod rsa_pem {
        use super::*;
        #[test]
        fn can_create_jwt() {
            let jwt = JWT::new_from_pem(String::from("./dev.pem"));
        }

        #[test]
        fn can_encode_jwt() {
            let jwt = JWT::new_from_pem(String::from("./dev.pem"));
            let claims = Claims::new(None, String::from("name"), String::from("email"), 15);
            let encoded_claims = jwt.encode(claims).unwrap();
        }

        #[test]
        fn can_decode_jwt() {
            let jwt = JWT::new_from_pem(String::from("./dev.pem"));
            let claims = Claims::new(Some(Uuid::new_v4()), String::from("name"), String::from("email"), 15);
            let token = jwt.encode(claims.clone()).unwrap();
            let token_data = jwt.decode(token).unwrap();

            assert_eq!(claims, token_data.claims);
        }
    }
}
