//! Module contains everything needed to handle JWT tokens generated by the frontend.
//! Encoding functions are included, but for testing purposes only, hence their 'private' status.

use uuid::Uuid;
use dotenvy::dotenv;
use jsonwebtoken::{ Algorithm, DecodingKey, Validation};
use std::time::{UNIX_EPOCH, SystemTime};
use serde::{Deserialize, Serialize};

/// Expected JWT TokenData claims from the frontend.
#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct Claims {
    /// Authenticated user's UUID (unique user ID, not just a sequential number).
    uuid: Uuid,
    /// Authenticated user's name.
    name: String,
    /// Authenticated user's email.
    email: String,
    /// Token expiration time in seconds from EPOCH.
    exp: usize,
}
impl Claims {
    /// Create a new Claims. Expiration should be in seconds from the claim creation on.
    /// Recommended exp: 5 to 15 minutes for API requests.
    ///
    /// The UUID is generated in-situ.
    /// ## Example
    /// ```
    /// let claims = Claims::new(
    ///     String::from("John Doe"),
    ///     String::from("john.doe@gmail.com"),
    ///     5 * 60 // 5 minutes from token creation on.
    /// )
    /// ```
    fn new(uuid: Uuid, name: String, email: String, exp: usize) -> Self {
        let now = SystemTime::now();
        let exp = now.duration_since(UNIX_EPOCH).unwrap().as_secs() as usize + exp;
        let uuid = uuid::Uuid::new_v4();

        Claims {
            uuid,
            name,
            email,
            exp
        }
    }
}
