-- This file should undo anything in `up.sql`
DROP TABLE IF EXISTS storage CASCADE;
DROP TABLE IF EXISTS drawers CASCADE;
DROP TABLE IF EXISTS freezers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS email_whitelist CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp";